from . import customer_catalogue
from . import pricelist
from . import product_product
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import stock_move
from . import account
